### PR TITLE
feat: Add createProducts

### PR DESCRIPTION
**Pull request by BohdanRSchool**
- [x] Task 4.1 is implemented
- [x] TASK 4.2 is implemented lambda links are provided and returns data
- [x] TASK 4.3 is implemented lambda links are provided and products is stored in DB (call TASK 4.2 to see the product)
- [x] Your own Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend. Link to a working Front-End application is provided for cross-check reviewer.

Additional (optional) tasks (but nice to have):
- [x] POST/products lambda functions returns error 400 status code if product data is invalid
- [x] All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
- [x] All lambdas do console.log for each incoming requests and their arguments
- [x] Transaction based creation of product (in case stock creation is failed then related to this stock product is not created and not ready to be used by the end user and vice versa)

Task 4.1 **SQL scripts**: product-service/data/script.sql
Task 4.2 **getProducts**: https://uxm7hab1p4.execute-api.eu-west-1.amazonaws.com/dev/products
             **getProductsById**: https://uxm7hab1p4.execute-api.eu-west-1.amazonaws.com/dev/products/e535e245-5fec-4b48-947c-6b882a9ffa97
Task 4.3 **createProducts**: https://uxm7hab1p4.execute-api.eu-west-1.amazonaws.com/dev/products
body
 `{
    "title": "L.O.L. Surprise! O.M.G. Remix Kitty K Fashion Doll",
    "description": "Unbox L.O.L. Surprise! O.M.G. Remix fashion doll Kitty K with 25 surprises.",
    "url": "https://images-na.ssl-images-amazon.com/images/I/71IpMYSqUnL._AC_SL1500_.jpg",
    "price": 39.99,
    "count": 9
}`

**FE pull request**: https://github.com/BohdanRSchool/nodejs-aws-fe/pull/3
**FE link**: https://d3qxm2chyskjsd.cloudfront.net/
**FE create product link**: https://d3qxm2chyskjsd.cloudfront.net/admin/product-form/

### CODE REVIEW

**Comment by numatay** [comment]
Hi @BohdanRSchool ,

When I try to create a new product on the web app, I get this error. It seems like you have not enabled CORS or not included relevant headers.

Would you mind fixing this bug?

image

**Comment by BohdanRSchool** [comment]
> Hi @BohdanRSchool ,
> 
> When I try to create a new product on the web app, I get this error. It seems like you have not enabled CORS or not included relevant headers.
> 
> Would you mind fixing this bug?
> 
> image

yes, I'll. Thanks

**Comment by BohdanRSchool** [comment]
@numatay fixed, thanks for the comment!

**Comment by numatay** [comment]
Hi @BohdanRSchool,

I tried to create a product with invalid data in the web app and it stored an invalid product in the database.
image

**Comment by numatay** [comment]
Cross-check review results:
- [x] TASK 4.1 is implemented. (Database, table creation scripts are provided). 
- [x] TASK 4.2 is implemented lambda links are provided and returns data
- [x] TASK 4.3 is implemented lambda links are provided and products is stored in DB
- [x]  Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend.
- [ ] +1 - POST/products lambda functions returns error 400 status code if product data is invalid
- [x] +1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
- [ ] +1 - All lambdas do console.log for each incoming requests and their arguments
- [x] +1 - Transaction based creation of product 

**Points earned**:  _7_ pts

**Comment by BohdanRSchool** [comment]
> Cross-check review results:
> 
> * [x]  TASK 4.1 is implemented. (Database, table creation scripts are provided).
> * [x]  TASK 4.2 is implemented lambda links are provided and returns data
> * [x]  TASK 4.3 is implemented lambda links are provided and products is stored in DB
> * [x]   Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend.
> * [ ]  +1 - POST/products lambda functions returns error 400 status code if product data is invalid
> * [x]  +1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
> * [ ]  +1 - All lambdas do console.log for each incoming requests and their arguments
> * [x]  +1 - Transaction based creation of product
> 
> **Points earned**: _7_ pts

It's because of data type validation. The type validation was implemented in the scope of the task. Didn't find requirements for the value validation. But thanks, it's a good point for improvement!

**Review by numatay — APPROVED** [review]

**Pull request merged**
