### PR TITLE
feat: Add import service

### PR DESCRIPTION
**Pull request by BohdanRSchool**
- [x] 1 - File serverless.yml contains configuration for importProductsFile function
- [x] 3 - The importProductsFile lambda function returns a correct response which can be used to upload a file into the S3 bucket
- [x] 4 - Frontend application is integrated with importProductsFile lambda
- [x] 5 - The importFileParser lambda function is implemented and serverless.yml contains configuration for the lambda
- [x] +1 - async/await is used in lambda functions
- [x] +1 - importProductsFile lambda is covered by unit tests (aws-sdk-mock can be used to mock S3 methods - https://www.npmjs.com/package/aws-sdk-mock)
- [x] +1 - At the end of the stream the lambda function should move the file from the uploaded folder into the parsed folder (move the file means that file should be copied into parsed folder, and then deleted from uploaded folder)

**FE pull request**: https://github.com/BohdanRSchool/nodejs-aws-fe/pull/4
**FE link**: https://d3qxm2chyskjsd.cloudfront.net/admin/products
**CSV File**: in the PR - import-service/data/username.csv

### CODE REVIEW

**Comment by Alex4Max** [comment]
I can't upload the file from your example (username.csv). 
Could you check, please, and let me know?

**Comment by BohdanRSchool** [comment]
> I can't upload the file from your example (username.csv).
> Could you check, please, and let me know?

Try this please
[username.zip](https://github.com/BohdanRSchool/nodejs-aws-be/files/5553483/username.zip)

**Comment by Alex4Max** [comment]
Still doesn't work even with your file

**Comment by BohdanRSchool** [comment]
> Still doesn't work even with your file

@Alex4Max I've set ContentType: 'application/vnd.ms-excel' beacuse I've uploaded files from Windows OS. For MacOs ContentType is 'text/csv'. I think this is the main reason. I'm not able to implement some workaroud for now, but I will be highly appreciated if you could check the uploading on the Windows OS. Thanks in advance.

**Comment by Alex4Max** [comment]
@BohdanRSchool I don't have a Windows machine) but in any case, i guess the main goal is to understand the issue. so i've changed my mark to 8 in cross-check

**Comment by BohdanRSchool** [comment]
> @BohdanRSchool I don't have a Windows machine) but in any case, i guess the main goal is to understand the issue. so i've changed my mark to 8 in cross-check

Thanks a lot @Alex4Max

**Pull request merged**
